// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BooksServices.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Book
    {
        /// <summary>
        /// Initializes a new instance of the Book class.
        /// </summary>
        public Book() { }

        /// <summary>
        /// Initializes a new instance of the Book class.
        /// </summary>
        public Book(int? bookId = default(int?), string title = default(string), string publisher = default(string), string isbn = default(string))
        {
            BookId = bookId;
            Title = title;
            Publisher = publisher;
            Isbn = isbn;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bookId")]
        public int? BookId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "publisher")]
        public string Publisher { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isbn")]
        public string Isbn { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Publisher != null)
            {
                if (this.Publisher.Length > 40)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Publisher", 40);
                }
            }
        }
    }
}
